USER_DIR := $(shell git rev-parse --show-toplevel)/riscv/sim/firmware
TEST_DIR = $(USER_DIR)/test
core = wish_riscv
SECTIONS := $(USER_DIR)/linker/sections.lds

DIR_COMMON := ""
INC_COMMON := ""

include /data/CATALOG_DIG_PG1_OA_DS/sync/python_env/hscpy/extra/riscv_firmware/Makefile
